// This file is auto-generated by Rails' stimulus:install command and sets up lazy loading for Stimulus controllers.
import { application } from "./application";

export const eagerLoadControllersFrom = require.context(
  "./",
  true,
  /_controller\.js$/
);
eagerLoadControllersFrom.keys().forEach(eagerLoadControllersFrom);

export const lazyLoadControllersFrom = (controllerPath) => {
  const controllerFilename = `./${controllerPath}_controller.js`;
  if (eagerLoadControllersFrom.keys().includes(controllerFilename)) {
    return eagerLoadControllersFrom(controllerFilename);
  }
  console.error(
    `Controller ${controllerPath} not found. Is it in the correct directory?`
  );
};
